version: '3.0'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
  server:
    image: server
    build: .
    environment:
      - DB_PASSWORD
      - DB_USER
      - DB_NAME
      - DB_HOST=db
    ports:
      - 3000:3000
    links:
      - db:db
    restart: unless-stopped
